export enum ErrorCode {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  TOKEN_VERSION_MISMATCH = 'TOKEN_VERSION_MISMATCH',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REUSED = 'REFRESH_TOKEN_REUSED',
  PASSWORD_MUST_BE_DIFFERENT = 'PASSWORD_MUST_BE_DIFFERENT',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  CANNOT_DEACTIVATE_SELF = 'CANNOT_DEACTIVATE_SELF',
}